### ISSUE TITLE
Integration: some homepage urls are wrong

### ISSUE THREAD

**Issue by pascal-brand38** [withastro/astro.build#1313]
https://astro.build/integrations/ lists all the npm package related to astro.
When selecting an integration, this links to the url page describing the integration.
Most of the time (apart when an issue has been filled to overwrite it), this url is the one found in package.json as "homepage".

Unfortunately, many of these urls are wrong. 48 "404" errors on homepage url, on a total of 690 integrations, which leads to a poor user experience.

As an example: integration "astro-github-stats" has the homepage https://ayco.io/showcase/astro-github-stats, which cannot be accessed. I guess it used to work at some point, but this is no more the case.

I propose: 
* to update scripts/update-integrations.mjs with an option to list wrong homepages
* update wrong urls with the npm url of the package. In the case of astro-github-stats, https://www.npmjs.com/package/astro-github-stats provides relevant information. This update could be done by the script, but a manual check may be useful. That's why I'm not sure whether such a script should be run on nightly or weekly build.

Let me know what you think of this, and if I should go toward this direction.

Do not hesitate to close this issue if you think this is dumb or if this was already discussed.

**Comment by delucis** [comment]
Hi @pascal-brand38! Thanks for the issue and for looking into this. I agree it would be better to avoid inaccurate URLs (although unfortunately it can indeed be hard to keep track once an integration is added to the directory).

I think your idea of having a known list of URLs that should be ignored by the script could work. Feel free to make a PR proposing those changes!

Ideally these URLs would be updated in the `package.json` of an integration itself, so that correct URLs are displayed on npm as well. But that would be tricky for us to do — especially in cases like the one you linked to where it’s not even clear where the source code is hosted, so we can’t even leave package authors an issue.
